export default {
  docs: [
    {
      type: "autogenerated",
      dirName: ".", // docs/
    }, // ad sits after the last real nav item
    {
      type: "html",
      value: `
        <div style="margin: 24px 12px 12px; padding-top: 14px; border-top: 1px solid var(--ifm-toc-border-color);">
          <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: var(--ifm-color-emphasis-600); margin-bottom: 10px;">From the Nodemailer team</div>
          <a href="https://emailengine.app/?utm_source=nodemailer.com&utm_medium=sidebar&utm_campaign=oss-docs" style="display: block; margin-bottom: 12px; text-decoration: none; color: var(--ifm-menu-color);">
            <span style="display: block; font-size: 14px; font-weight: 600;">EmailEngine</span>
            <span style="display: block; font-size: 12px; line-height: 1.45; color: var(--ifm-color-emphasis-700);">Self-hosted email API for Gmail, Microsoft 365, and IMAP</span>
          </a>
          <a href="https://imapflow.com/" style="display: block; margin-bottom: 12px; text-decoration: none; color: var(--ifm-menu-color);">
            <span style="display: block; font-size: 14px; font-weight: 600;">ImapFlow</span>
            <span style="display: block; font-size: 12px; line-height: 1.45; color: var(--ifm-color-emphasis-700);">Modern IMAP client library for Node.js</span>
          </a>
          <a href="https://ethereal.email/" style="display: block; text-decoration: none; color: var(--ifm-menu-color);">
            <span style="display: block; font-size: 14px; font-weight: 600;">Ethereal</span>
            <span style="display: block; font-size: 12px; line-height: 1.45; color: var(--ifm-color-emphasis-700);">Fake SMTP service for testing email sending</span>
          </a>
        </div>
      `,
      defaultStyle: false, // keeps Docusaurus from restyling it as a list item
    },
  ],
};
